### ISSUE TITLE
jaeger ingester panic with deadlockInterval > 0

### ISSUE THREAD

**Issue by huikang** [jaegertracing/jaeger-operator#1013]
I observe the ingested keeps restarting due to a panic when I set `deadlockInterval: 5s` (as shown in the [doc](https://www.jaegertracing.io/docs/1.17/operator/#existing-kafka-cluster)).

```
"level":"panic","ts":1586465229.2084777,"caller":"consumer/deadlock_detector.go:71","msg":"No messages processed in the last check interval","partition":-1,"stack":"goroutine 56 [running]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1(0xc0ffffffff)\n\tgithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:73 +0x24d\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1(0xc000328090, 0xc0002901a0)\n\tgithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163 +0x148\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start\n\tgithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:152 +0x185\n\ngoroutine 1 [select]:\ngithub.com/jaegertracing/jaeger/cmd/flags.(*Service).RunAndThen(0xc0001b0200, 0xc0001298a8)\n\tgithub.com/jaegertracing/jaeger/cmd/flags/service.go:137 +0xf3\nmain.main.func1(0xc0001f6900, 0xc0001b1a40, 0x0, 0x4, 0x0, 0x0)\n\tcommand-line-arguments/main.go:78 +0x84f\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001f6900, 0xc0000bc010, 0x4, 0x4, 0xc0001f6900, 0xc0000bc010)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:698 +0x42c\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f6900, 0xc0001f6900, 0xc000129ee8, 0x3)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:783 +0x2c9\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute(...)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:736\nmain.main()\n\tcommand-line-arguments/main.go:105 +0x568\n\ngoroutine 19 [syscall]:\nos/signal.signal_recv(0x0)\n\truntime/sigqueue.go:147 +0x9c\nos/signal.loop()\n\tos/signal/signal_unix.go:23 +0x22\ncreated by os/signal.init.0\n\tos/signal/signal_unix.go:29 +0x41\n\ngoroutine 37 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f4769d2b028, 0x72, 0x0)\n\truntime/netpoll.go:184 +0x55\ninternal/poll.(*pollDesc).wait(0xc0001bc498, 0x72, 0x0, 0x0, 0x12642d0)\n\tinternal/poll/fd_poll_runtime.go:87 +0x45\ninternal/poll.(*pollDesc).waitRead(...)\n\tinternal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Accept(0xc0001bc480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\tinternal/poll/fd_unix.go:384 +0x1f8\nnet.(*netFD).accept(0xc0001bc480, 0xc000092cc8, 0xc000059180, 0x7f476bf93008)\n\tnet/fd_unix.go:238 +0x42\nnet.(*TCPListener).accept(0xc000290020, 0xc000092cf8, 0x40ca28, 0x30)\n\tnet/tcpsock_posix.go:139 +0x32\nnet.(*TCPListener).Accept(0xc000290020, 0x117e360, 0xc0001a6ba0, 0x10a1420, 0x1d57c20)\n\tnet/tcpsock.go:261 +0x47\nnet/http.(*Server).Serve(0xc0002a2000, 0x1427980, 0xc000290020, 0x0, 0x0)\n\tnet/http/server.go:2896 +0x280\ngithub.com/jaegertracing/jaeger/cmd/flags.(*AdminServer).serveWithListener.func1(0xc0001ad260, 0x1427980, 0xc000290020)\n\tgithub.com/jaegertracing/jaeger/cmd/flags/admin.go:123 +0x61\ncreated by github.com/jaegertracing/jaeger/cmd/flags.(*AdminServer).serveWithListener\n\tgithub.com/jaegertracing/jaeger/cmd/flags/admin.go:122 +0x3ff\n\ngoroutine 44 [select]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic.(*Client).healthchecker(0xc0001f4b60)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic/client.go:1054 +0x179\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic.DialContext\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic/client.go:404 +0x5ae\n\ngoroutine 7 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f4769d2ae88, 0x72, 0xffffffffffffffff)\n\truntime/netpoll.go:184 +0x55\ninternal/poll.(*pollDesc).wait(0xc000444198, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)\n\tinternal/poll/fd_poll_runtime.go:87 +0x45\ninternal/poll.(*pollDesc).waitRead(...)\n\tinternal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Read(0xc000444180, 0xc00044e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\tinternal/poll/fd_unix.go:169 +0x1cf\nnet.(*netFD).Read(0xc000444180, 0xc00044e000, 0x1000, 0x1000, 0x43133c, 0xc000093b20, 0x45bbd0)\n\tnet/fd_unix.go:202 +0x4f\nnet.(*conn).Read(0xc00000e0b8, 0xc00044e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\tnet/net.go:184 +0x68\nnet/http.(*persistConn).Read(0xc0001c5320, 0xc00044e000, 0x1000, 0x1000, 0xc00024a180, 0xc000093c20, 0x404d15)\n\tnet/http/transport.go:1758 +0x75\nbufio.(*Reader).fill(0xc000076960)\n\tbufio/bufio.go:100 +0x103\nbufio.(*Reader).Peek(0xc000076960, 0x1, 0x0, 0x0, 0x1, 0xc00045c700, 0x0)\n\tbufio/bufio.go:138 +0x4f\nnet/http.(*persistConn).readLoop(0xc0001c5320)\n\tnet/http/transport.go:1911 +0x1d6\ncreated by net/http.(*Transport).dialConn\n\tnet/http/transport.go:1580 +0xb0d\n\ngoroutine 66 [select]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic.(*bulkWorker).work(0xc0001b1f80, 0x142d6c0, 0xc0000b2010)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic/bulk_processor.go:480 +0x125\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic.(*BulkProcessor).Start\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic/bulk_processor.go:336 +0x1e4\n\ngoroutine 57 [chan receive]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1(0xc000328000)\n\tgithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:79 +0x187\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start\n\tgithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:77 +0x56\n\ngoroutine 8 [select]:\nnet/http.(*persistConn).writeLoop(0xc0001c5320)\n\tnet/http/transport.go:2210 +0x123\ncreated by net/http.(*Transport).dialConn\n\tnet/http/transport.go:1581 +0xb32\n\ngoroutine 67 [select]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic.(*BulkProcessor).flusher(0xc0001bfba0, 0xbebc200)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic/bulk_processor.go:429 +0x10d\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic.(*BulkProcessor).Start\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/olivere/elastic/bulk_processor.go:342 +0x445\n\ngoroutine 28 [select]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*client).backgroundMetadataUpdater(0xc000452120)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/client.go:713 +0x15d\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.withRecover(0xc0002f6230)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/utils.go:45 +0x4d\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.NewClient\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/client.go:172 +0x546\n\ngoroutine 26 [chan receive]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x1d71260)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/rcrowley/go-metrics/meter.go:239 +0x31\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/rcrowley/go-metrics.NewMeter\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/rcrowley/go-metrics/meter.go:46 +0x111\n\ngoroutine 27 [chan receive]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).responseReceiver(0xc00009c000)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:790 +0xc7\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.withRecover(0xc0002f61f0)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/utils.go:45 +0x4d\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).Open.func1\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:215 +0x99e\n\ngoroutine 54 [select]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).sendAndReceive(0xc00015e000, 0x1430580, 0xc000076360, 0x140cf80, 0xc0000bc5a0, 0x0, 0xc00036a200)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:717 +0x145\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).JoinGroup(0xc00015e000, 0xc000076360, 0xf, 0xc00015e000, 0x0)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:396 +0x70\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*Consumer).joinGroup(0xc00045e0f0, 0xc000290220, 0x3, 0xc000290220)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/consumer.go:669 +0x308\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*Consumer).rebalance(0xc00045e0f0, 0x0, 0x0, 0xc0000bbc40)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/consumer.go:577 +0x179\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*Consumer).nextTick(0xc00045e0f0)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/consumer.go:363 +0xa1\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*Consumer).mainLoop(0xc00045e0f0)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/consumer.go:334 +0xc8\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.NewConsumerFromClient\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/consumer.go:96 +0x3da\n\ngoroutine 29 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f4769d2af58, 0x72, 0xffffffffffffffff)\n\truntime/netpoll.go:184 +0x55\ninternal/poll.(*pollDesc).wait(0xc000116418, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)\n\tinternal/poll/fd_poll_runtime.go:87 +0x45\ninternal/poll.(*pollDesc).waitRead(...)\n\tinternal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Read(0xc000116400, 0xc000486000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\tinternal/poll/fd_unix.go:169 +0x1cf\nnet.(*netFD).Read(0xc000116400, 0xc000486000, 0x1000, 0x1000, 0xc000116400, 0xc000305d00, 0xc000305cf0)\n\tnet/fd_unix.go:202 +0x4f\nnet.(*conn).Read(0xc0000b4058, 0xc000486000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\tnet/net.go:184 +0x68\nbufio.(*Reader).Read(0xc000351ce0, 0xc0003ba098, 0x8, 0x8, 0x40904b, 0xc00001e000, 0x10c94a0)\n\tbufio/bufio.go:226 +0x26a\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*bufConn).Read(0xc0001b4560, 0xc0003ba098, 0x8, 0x8, 0xc000305df8, 0x40a195, 0x10c94a0)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/utils.go:109 +0x4d\nio.ReadAtLeast(0x7f4769d2f488, 0xc0001b4560, 0xc0003ba098, 0x8, 0x8, 0x8, 0x1d71860, 0xc000305ec0, 0x40523a)\n\tio/io.go:310 +0x87\nio.ReadFull(...)\n\tio/io.go:329\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).responseReceiver(0xc00015e000)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:803 +0x290\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.withRecover(0xc0002f63d0)\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/utils.go:45 +0x4d\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).Open.func1\n\tgithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:215 +0x99e\n","stacktrace":"github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1\n\tgithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1\n\tgithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163"}
panic: No messages processed in the last check interval

goroutine 56 [running]:
github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0002342c0, 0xc0001bc080, 0x2, 0x2)
	github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/zapcore/entry.go:230 +0x546
github.com/jaegertracing/jaeger/vendor/go.uber.org/zap.(*Logger).Panic(0xc0001aa660, 0x1294f0f, 0x30, 0xc0001bc080, 0x2, 0x2)
	github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/logger.go:225 +0x7f
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1(0xc0ffffffff)
	github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71 +0x40d
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1(0xc000328090, 0xc0002901a0)
	github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163 +0x148
created by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start
	github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:152 +0x185

```

However, if I disabled the deadlockInterval or set to 0s, the problem disappears. Does anyone else have the same issue or is this a bug? Thanks.

**Comment by objectiser** [comment]
This is expected behaviour - if no messages are received within the defined time period the ingester is terminated in case it is due to a deadlock, enabling the environment (e.g. kubernetes) to restart it. As described in the CLI flag description: "Interval to check for deadlocks. If no messages gets processed in given time, ingester app will exit. Value of 0 disables deadlock check."

**Comment by huikang** [comment]
@objectiser , thanks for your answer, so I will ignore the restart in my deployment.

However, I think `panic` is different than `exit`, say with code 1. This seems a bug to me.

**Comment by objectiser** [comment]
@yurishkuro Any idea why it used panic vs just warning with an exit?

**Comment by yurishkuro** [comment]
Panic gives you a stack trace. I don't think any more thoughts went into it than that.

**Comment by huikang** [comment]
> Panic gives you a stack trace. I don't think any more thoughts went into it than that.

Thanks.
