### ISSUE TITLE
jaeger-spark-dependencies - OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by schewara** [jaegertracing/jaeger-operator#1131]
Hi Everyone

Currently I'm seeing some weird behaviour that all the Jobs are failing with OutOfMemoryErrors while the resource Limits never seem to be reached.

The max Memory Usage from the Pod is `~ 515MB` before it crashes

Therefore I was wondering if any of you ran into this issue and how to solve it.
In addition, I was also wondering if there is a way to set explicit Memory settings (-Xms and -Xmx) through a JAVA_OPTIONS Variable or some other way through the CRDs

The Log output:
```
20/07/10 11:10:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/07/10 11:10:20 INFO ElasticsearchDependenciesJob: Running Dependencies job for 2020-07-10T00:00Z, reading from testing-jaeger-span-2020-07-10 index, result storing to testing-jaeger-dependencies-2020-07-10
20/07/10 11:42:19 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator$$anonfun$4.apply(ShuffleBlockFetcherIterator.scala:422)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator$$anonfun$4.apply(ShuffleBlockFetcherIterator.scala:422)
	at org.apache.spark.util.io.ChunkedByteBufferOutputStream.allocateNewChunkIfNeeded(ChunkedByteBufferOutputStream.scala:87)
	at org.apache.spark.util.io.ChunkedByteBufferOutputStream.write(ChunkedByteBufferOutputStream.scala:75)
	at org.apache.spark.util.Utils$$anonfun$copyStream$1.apply$mcJ$sp(Utils.scala:347)
	at org.apache.spark.util.Utils$$anonfun$copyStream$1.apply(Utils.scala:332)
	at org.apache.spark.util.Utils$$anonfun$copyStream$1.apply(Utils.scala:332)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.util.Utils$.copyStream(Utils.scala:353)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator.next(ShuffleBlockFetcherIterator.scala:427)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator.next(ShuffleBlockFetcherIterator.scala:61)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:32)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:153)
	at org.apache.spark.Aggregator.combineValuesByKey(Aggregator.scala:41)
	at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala:90)
	at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:105)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
20/07/10 11:42:20 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker for task 1,5,main]
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator$$anonfun$4.apply(ShuffleBlockFetcherIterator.scala:422)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator$$anonfun$4.apply(ShuffleBlockFetcherIterator.scala:422)
	at org.apache.spark.util.io.ChunkedByteBufferOutputStream.allocateNewChunkIfNeeded(ChunkedByteBufferOutputStream.scala:87)
	at org.apache.spark.util.io.ChunkedByteBufferOutputStream.write(ChunkedByteBufferOutputStream.scala:75)
	at org.apache.spark.util.Utils$$anonfun$copyStream$1.apply$mcJ$sp(Utils.scala:347)
	at org.apache.spark.util.Utils$$anonfun$copyStream$1.apply(Utils.scala:332)
	at org.apache.spark.util.Utils$$anonfun$copyStream$1.apply(Utils.scala:332)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.util.Utils$.copyStream(Utils.scala:353)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator.next(ShuffleBlockFetcherIterator.scala:427)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator.next(ShuffleBlockFetcherIterator.scala:61)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.util.CompletionIterator.hasNext(CompletionIterator.scala:32)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:153)
	at org.apache.spark.Aggregator.combineValuesByKey(Aggregator.scala:41)
	at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala:90)
	at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:105)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
```

Elasticsearch Index Info:
```
Docs Count:    36135444
Storage Size:   2.4gb
```

And the Job output from describe
```
Name:           jaeger-spark-dependencies-manual-56m
Namespace:      jaeger
Selector:       controller-uid=dc2a5e1d-4d0f-430c-b53b-06d1f5693198
Labels:         app=jaeger
                app.kubernetes.io/component=spark-dependencies
                app.kubernetes.io/instance=jaeger
                app.kubernetes.io/managed-by=jaeger-operator
                app.kubernetes.io/name=jaeger-spark-dependencies
                app.kubernetes.io/part-of=jaeger
                controller-uid=dc2a5e1d-4d0f-430c-b53b-06d1f5693198
                job-name=jaeger-spark-dependencies-manual-56m
Annotations:    cronjob.kubernetes.io/instantiate: manual
Parallelism:    1
Completions:    <unset>
Start Time:     Fri, 10 Jul 2020 13:10:06 +0200
Pods Statuses:  1 Running / 0 Succeeded / 2 Failed
Pod Template:
  Labels:           app=jaeger
                    app.kubernetes.io/component=spark-dependencies
                    app.kubernetes.io/instance=jaeger
                    app.kubernetes.io/managed-by=jaeger-operator
                    app.kubernetes.io/name=jaeger-spark-dependencies
                    app.kubernetes.io/part-of=jaeger
                    controller-uid=dc2a5e1d-4d0f-430c-b53b-06d1f5693198
                    job-name=jaeger-spark-dependencies-manual-56m
  Annotations:      linkerd.io/inject: disabled
                    prometheus.io/scrape: false
                    sidecar.istio.io/inject: false
  Service Account:  jaeger
  Containers:
   jaeger-spark-dependencies:
    Image:      <internalrepo>/jaegertracing/spark-dependencies
    Port:       <none>
    Host Port:  <none>
    Limits:
      memory:  4Gi
    Requests:
      memory:  4Gi
    Environment:
      STORAGE:          elasticsearch
      ES_NODES:         xxx
      ES_INDEX_PREFIX:  xxx
      ES_USERNAME:      xxx
      ES_PASSWORD:      xxx
    Mounts:             <none>
  Volumes:              <none>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  54m   job-controller  Created pod: jaeger-spark-dependencies-manual-56m-4gdr4
  Normal  SuccessfulCreate  21m   job-controller  Created pod: jaeger-spark-dependencies-manual-56m-xfg2q
```
The actual Docker Image version: 
`jaegertracing/spark-dependencies@sha256:3dc11f9a8a2fc6aff2f6cbd002de194f89bb1beb9c2e79834693cc722a3bd84a`

**Comment by jpkrohling** [comment]
> while the resource Limits never seem to be reached.

Does sound like improper Xmx/Xms. Have you changed any options at all, like setting the limits/requests?

>  In addition, I was also wondering if there is a way to set explicit Memory settings (-Xms and -Xmx) through a JAVA_OPTIONS Variable or some other way through the CRDs

Yes: https://github.com/jaegertracing/jaeger-operator/blob/f6067194b9787e1ca2cf226f70925b723784d397/pkg/apis/jaegertracing/v1/jaeger_types.go#L498

Basically:

```yaml
spec:
  storage:
    dependencies:
      javaOpts: "-Xmx... -Xms..."
```

**Comment by schewara** [comment]
@jpkrohling Thanks for the update
I finally found the `javaOpts` setting and it somehow improves the situation and probably have to tweak the settings some more,
as it seems, the memory consumption is very unpredictable and some jobs finish within 10min and other take forever.

```
$ k get pods
NAME                                         READY   STATUS      RESTARTS   AGE
jaeger-spark-dependencies-1599695700-45gkd   0/1     Error       0          18h
jaeger-spark-dependencies-1599695700-8rz9v   0/1     Error       0          21h
jaeger-spark-dependencies-1599695700-9l96c   0/1     Error       0          13h
jaeger-spark-dependencies-1599695700-gpbbx   0/1     Error       0          16h
jaeger-spark-dependencies-1599695700-hgc2p   0/1     Error       0          10h
jaeger-spark-dependencies-1599782100-2hcrj   0/1     Completed   0          8h

$ k get jobs
NAME                                   COMPLETIONS   DURATION   AGE
jaeger-spark-dependencies-1598572500   1/1           56m        14d
jaeger-spark-dependencies-1598658900   1/1           91m        13d
jaeger-spark-dependencies-1599695700   0/1           34h        34h
jaeger-spark-dependencies-1599782100   1/1           11m        8h
```
I guess I need to dig a bit deeper into the raw data to figure out what's happening here.

But thanks a lot and I will close this Ticket, as the original problem with the jvm Heap is solved.

**Comment by jpkrohling** [comment]
> I guess I need to dig a bit deeper into the raw data to figure out what's happening here.

Once you figure this out, do let us know if there's something to improve in the job.
