### ISSUE TITLE
Cassandra schema job is failed when `options.cassandra.servers` has multi server address list

### ISSUE THREAD

**Issue by anarcher** [jaegertracing/jaeger-operator#1487]
**Describe the bug**
Cassandra schema job is failed when `options.cassandra.servers` has multi-server address list (Docker image version is: `jaeger-operator:1.22.1`)

logs from `jaeger-cassandra-schema-job`

```
socket.gaierror: [Errno -2] Name or service not known
Cassandra is still not up at scylla-jaegerdb-dc1-a1-0,scylla-jaegerdb-dc1-a1-1,scylla-jaegerdb-dc1-a1-2:9042. Waiting 1 second.
Traceback (most recent call last):
  File "/opt/cassandra/bin/cqlsh.py", line 2458, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "/opt/cassandra/bin/cqlsh.py", line 2436, in main
    encoding=options.encoding)
  File "/opt/cassandra/bin/cqlsh.py", line 484, in __init__
    load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
  File "/opt/cassandra/bin/../lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/policies.py", line 417, in __init__
socket.gaierror: [Errno -2] Name or service not known
Timed out waiting for Cassandra.
```

`jaeger` CRD

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  allInOne:
    options:
      collector.zipkin.host-port: "9411"
      log-level: debug
  storage:
    cassandraCreateSchema:
      datacenter: dc1
      enabled: true
      mode: test
    options:
      cassandra:
        keyspace: jaeger_v1_dc1
        servers: scylla-jaegerdb-dc1-a1-0,scylla-jaegerdb-dc1-a1-1,scylla-jaegerdb-dc1-a1-2
    type: cassandra
  strategy: allinone
```

**To Reproduce**
1.  
2.
3.

**Expected behavior**

Successfully done of Cassandra schema job

**Screenshots**

**Version (please complete the following information):**
Docker image version is: `jaeger-operator:1.22.1`

**What troubleshooting steps did you try?**
If `cassandra.servers` has single server address, This job runs successfully.

**Additional context**
I am not sure but it is ok for me  that  choosing first `cassandra.servers` when creating job .
What do you think about it? :-> 

https://github.com/jaegertracing/jaeger-operator/blob/b98361cf4a8fc05e558001b310114aa5e57f8c35/pkg/storage/cassandra_dependencies.go#L47

```
host := jaeger.Spec.Storage.Options.Map()["cassandra.servers"]
host = string.Split(host,",")[0]  //  <- choose first server address 
if host == "" {
   jaeger.Logger().Info("Cassandra hostname not specified. Using 'cassandra' for the cassandra-create-schema job.")
   host = "cassandra" // this is the default in the image
}
```

**Comment by jpkrohling** [comment]
>  I am not sure but it is ok for me that choosing first cassandra.servers when creating job .

Sounds reasonable to me.

**Comment by immanu2** [comment]
Hi @jpkrohling! I'd like to take a look at this issue and submit a fix. Could you assign it to me?
