### ISSUE TITLE
Jaeger Ingester CrashLoop - Invalid Memory Address

### ISSUE THREAD

**Issue by rblaine95** [jaegertracing/jaeger-operator#1899]
**Describe the bug**
Jaeger Ingester starts up and then crashes while starting handlers for Kafka partitions:
```
# kubectl logs -f jaeger-ingester-5c8c789b9-nm8ww
2022/05/24 09:58:41 maxprocs: Updating GOMAXPROCS=8: determined from CPU quota
{"level":"info","ts":1653386321.7027373,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1653386321.702781,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1653386321.7029285,"caller":"flags/admin.go:104","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1653386321.7029817,"caller":"flags/admin.go:115","msg":"Starting admin HTTP server","http-addr":":14270"}
{"level":"info","ts":1653386321.7030063,"caller":"flags/admin.go:96","msg":"Admin server started","http.host-port":"[::]:14270","health-status":"unavailable"}
{"level":"info","ts":1653386321.7990947,"caller":"config/config.go:206","msg":"Elasticsearch detected","version":7}
{"level":"info","ts":1653386321.9024146,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1653386321.9024808,"caller":"consumer/consumer.go:79","msg":"Starting main loop"}
{"level":"info","ts":1653386348.6559582,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":2}
{"level":"info","ts":1653386348.6560001,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":2}
{"level":"info","ts":1653386348.6559901,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":5}
{"level":"info","ts":1653386348.6560426,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":5}
{"level":"info","ts":1653386348.6561007,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":8}
{"level":"info","ts":1653386348.6561055,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":8}
{"level":"info","ts":1653386348.6564558,"caller":"consumer/processor_factory.go:65","msg":"Creating new processors","partition":2}
{"level":"info","ts":1653386348.660941,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":4}
{"level":"info","ts":1653386348.6608953,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":4}
{"level":"info","ts":1653386348.6615567,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":1}
{"level":"info","ts":1653386348.6617696,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":7}
{"level":"info","ts":1653386348.6618035,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":7}
{"level":"info","ts":1653386348.6617985,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":1}
{"level":"info","ts":1653386348.6655865,"caller":"consumer/processor_factory.go:65","msg":"Creating new processors","partition":8}
{"level":"info","ts":1653386348.6658897,"caller":"consumer/processor_factory.go:65","msg":"Creating new processors","partition":5}
{"level":"info","ts":1653386348.6895201,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":0}
{"level":"info","ts":1653386348.6895962,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":9}
{"level":"info","ts":1653386348.6896307,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":3}
{"level":"info","ts":1653386348.6896472,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":3}
{"level":"info","ts":1653386348.6896658,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":6}
{"level":"info","ts":1653386348.6896265,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":9}
{"level":"info","ts":1653386348.6897225,"caller":"consumer/consumer.go:167","msg":"Starting error handler","partition":6}
{"level":"info","ts":1653386348.689735,"caller":"consumer/consumer.go:110","msg":"Starting message handler","partition":0}
{"level":"info","ts":1653386348.700216,"caller":"consumer/processor_factory.go:65","msg":"Creating new processors","partition":7}
{"level":"info","ts":1653386348.7057273,"caller":"consumer/processor_factory.go:65","msg":"Creating new processors","partition":4}
{"level":"info","ts":1653386348.705963,"caller":"consumer/processor_factory.go:65","msg":"Creating new processors","partition":1}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xdcee46]

goroutine 1245 [running]:
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.convertProcess(...)
	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:123
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.convertSpanEmbedProcess({0xa0?, 0xc0005e62a0?, {0x1513328?, 0xf5f132?}}, 0xc0000fc4b0)
	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:64 +0x126
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.FromDomainEmbedProcess(...)
	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:43
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan(0xc0005e4e40, {0x0?, 0x0?}, 0xc0000fc4b0)
	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:152 +0x7a
github.com/jaegertracing/jaeger/cmd/ingester/app/processor.KafkaSpanProcessor.Process({{0x1517400, 0x1d91150}, {0x1517280, 0xc0005e4e40}, {0x0, 0x0}}, {0x15197c0?, 0xc002137040?})
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/span_processor.go:67 +0xd3
github.com/jaegertracing/jaeger/cmd/ingester/app/processor/decorator.(*retryDecorator).Process(0xc0001de070, {0x15197c0, 0xc002137040})
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/decorator/retry.go:110 +0x37
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*comittingProcessor).Process(0xc00208e330, {0x15197c0, 0xc002137040})
	github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/committing_processor.go:44 +0x5e
github.com/jaegertracing/jaeger/cmd/ingester/app/processor.(*metricsDecorator).Process(0xc000968100, {0x15197c0, 0xc002137040})
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/metrics_decorator.go:44 +0x5b
github.com/jaegertracing/jaeger/cmd/ingester/app/processor.(*ParallelProcessor).Start.func1()
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/parallel_processor.go:57 +0x42
created by github.com/jaegertracing/jaeger/cmd/ingester/app/processor.(*ParallelProcessor).Start
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/parallel_processor.go:53 +0xf5
```

**To Reproduce**
1. Deploy Jaeger in Streaming mode pointing to Kafka (`2.8.1`) and OpenSearch (`1.2.2`) (see yaml manifest below)
2. Everything starts up without issue except Jaeger Ingester

**Expected behavior**
Jaeger Ingester should start up without issue.

**Version (please complete the following information):**
 - OS: Amazon Linux 2 running EKS 1.21
 - Jaeger version: 1.34.1
 - Deployment: AWS EKS 1.21

**What troubleshooting steps did you try?**
Initially I thought it may be due to resource constraints (OOM), so bumped memory req/limit from `128Mi` to `4096Mi`, issue persisted.
Also added `--log-level=debug` and was absolutely inundated with logs, the only thing that really caught my eye was the following log that happens just before the pod dies:
```json
{
  "level": "debug",
  "ts": 1653392657.9042532,
  "caller": "consumer/consumer.go:138",
  "msg": "Got msg",
  "msg": {
    "Headers": null,
    "Timestamp": "0001-01-01T00:00:00Z",
    "BlockTimestamp": "0001-01-01T00:00:00Z",
    "Key": null,
    "Value": null,
    "Topic": "jaeger-spans",
    "Partition": 4,
    "Offset": 3098
  }
}

```
Whereas the other logs are like this:
```json
{
  "level": "debug",
  "ts": 1653392657.8999662,
  "caller": "consumer/consumer.go:138",
  "msg": "Got msg",
  "msg": {
    "Headers": null,
    "Timestamp": "0001-01-01T00:00:00Z",
    "BlockTimestamp": "0001-01-01T00:00:00Z",
    "Key": "Base64EncodedKey",
    "Value": "Base64EncodedValue",
    "Topic": "jaeger-spans",
    "Partition": 4,
    "Offset": 3097
  }
}
```
To my untrained eye, it looks like a Jaeger is trying to ingest a `null` message in Kafka and it's causing the memory error above?

**Additional context**
Jaeger config:
```yaml
# kubectl get jaeger jaeger -o yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  annotations:
    meta.helm.sh/release-name: istio-monitoring
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2021-12-10T12:18:26Z"
  generation: 23
  labels:
    app.kubernetes.io/instance: istio-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-monitoring
    component: jaeger
    helm.sh/chart: istio-monitoring-0.1.1
    jaegertracing.io/operated-by: istio-operator.jaeger-operator
  name: jaeger
  namespace: monitoring
  resourceVersion: "444063604"
  uid: 67f960fc-d7f1-424c-8974-f3b8823b1d4e
spec:
  agent:
    config: {}
    options: {}
    resources: {}
  allInOne:
    config: {}
    metricsStorage: {}
    options: {}
    resources: {}
  collector:
    config: {}
    options:
      kafka:
        producer:
          brokers: kafka-brokers.example-namespace:9092
          topic: jaeger-spans
    resources: {}
  ingester:
    config: {}
    options:
      kafka:
        consumer:
          brokers: kafka-brokers.example-namespace:9092
          topic: jaeger-spans
    resources:
      limits:
        cpu: "1"
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 128Mi
  ingress:
    enabled: false
    openshift: {}
    options: {}
    resources: {}
    security: none
  query:
    metricsStorage: {}
    options: {}
    resources: {}
  resources: {}
  sampling:
    options: {}
  storage:
    cassandraCreateSchema: {}
    dependencies:
      enabled: true
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      name: elasticsearch
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: "1"
          memory: 16Gi
      storage: {}
    esIndexCleaner:
      enabled: true
      numberOfDays: 7
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      resources: {}
      schedule: 0 0 * * *
    grpcPlugin: {}
    options:
      es:
        index-prefix: monitoring
        server-urls: https://opensearch.example.org:443
    secretName: jaeger-es-creds
    type: elasticsearch
  strategy: streaming
  ui:
    options: {}
```

**Comment by frzifus** [comment]
hi @rblaine95 let me point you here: https://github.com/jaegertracing/jaeger/issues/3578

**Comment by rblaine95** [comment]
Thank you @frzifus, I'll close this issue as a duplicate of https://github.com/jaegertracing/jaeger/issues/3578

**Comment by rblaine95** [comment]
Just want to leave a quick update:

Luckily this was identified in our Dev cluster, so we could roll out the `1.34` fix in Prod before anything went sideways.
Also, it's Dev, nothing very important in there, so we just scaled jaeger down to zero, deleted the kafka topic, and then scaled back up.

Thank you for directing me to the other issue @frzifus ❤️
