### ISSUE TITLE
[Bug]: Nil pointer dereference when injecting jaeger-agent to deployment with secretRef envFrom

### ISSUE THREAD

**Issue by edwardecook** [jaegertracing/jaeger-operator#2341]
### What happened?

As a Jaeger operator user
I want the Jaeger operator to be able to inject the jaeger-agent into deployments which use `envFrom.secretRef`
so that I can continue to use Jaeger operator with my preexisting deployment configurations

### Steps to reproduce

1. Deploy a jaeger-operator v1.48.1+ watching all namespaces
2. Apply the test-deployment `Deployment` and corresponding `Secret` and `ConfigMap` from "Deployment configs" section
3. Check the deployment and see that a jaeger-agent has not been injected
4. Check the logs for the jaeger-operator and see that jaeger agent injection failed

### Expected behavior

The jaeger-agent should be injected into the deployment.

### Relevant log output

```shell
2023-10-10T09:53:29Z	INFO	verify deployment	{"namespace": "test-ns"}
2023-10-10T09:53:29Z	INFO	annotation present on deployment	{"namespace": "test-ns", "deployment": "test-deployment"}
2023-10-10T09:53:29Z	INFO	injecting Jaeger Agent sidecar	{"namespace": "test-ns", "jaeger": "jaeger", "jaeger-namespace": "tools"}
2023/10/10 09:53:29 http: panic serving 172.16.0.11:40524: runtime error: invalid memory address or nil pointer dereference
goroutine 26434 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x19b0e20, 0x2bfeb50})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/jaegertracing/jaeger-operator/pkg/inject.GetConfigMapsMatchedEnvFromInDeployment(...)
	/workspace/pkg/inject/sidecar.go:527
github.com/jaegertracing/jaeger-operator/controllers/appsv1.(*deploymentInterceptor).Handle(_, {_, _}, {{{0xc000658e70, 0x24}, {{0xc000bb4548, 0x4}, {0xc000bb454c, 0x2}, {0xc000bb4580, ...}}, ...}})
	/workspace/controllers/appsv1/deployment_webhook.go:141 +0x1e94
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc000658e70, 0x24}, {{0xc000bb4548, 0x4}, {0xc000bb454c, 0x2}, {0xc000bb4580, ...}}, ...}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/webhook/admission/webhook.go:169 +0x20a
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc000258c80, {0x7f230bdfe8e0?, 0xc000402e10}, 0xc000703400)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/webhook/admission/http.go:98 +0xc94
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7f230bdfe8e0, 0xc000402e10}, 0x1ed1400?)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/promhttp/instrument_server.go:60 +0xd4
net/http.HandlerFunc.ServeHTTP(0x1ed1490?, {0x7f230bdfe8e0?, 0xc000402e10?}, 0xc000631828?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x1ed1490?, 0xc0008756c0?}, 0xc000703400)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/promhttp/instrument_server.go:147 +0xc5
net/http.HandlerFunc.ServeHTTP(0x77f925?, {0x1ed1490?, 0xc0008756c0?}, 0x7f2333593a68?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x1ed1490, 0xc0008756c0}, 0xc000703400)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/promhttp/instrument_server.go:109 +0xc7
net/http.HandlerFunc.ServeHTTP(0xc0008756c0?, {0x1ed1490?, 0xc0008756c0?}, 0x1beaa15?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc000658e2b?, {0x1ed1490, 0xc0008756c0}, 0xc000703400)
	/usr/local/go/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0x1ec24d0?}, {0x1ed1490, 0xc0008756c0}, 0xc000703400)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc00065ab40, {0x1ed24b8, 0xc000678120})
	/usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed
```

### Additional context

This was not an issue with earlier versions of the jaeger-operator. We believe the issue stems from https://github.com/jaegertracing/jaeger-operator/pull/2272 which does not account for `envFrom`s using `secretRef` rather than `configMapRef` causing a nil pointer dereference.

### Jaeger backend version

v1.48.1

### Deployment model

Kubernetes

### Deployment configs

```shell
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  annotations:
    sidecar.jaegertracing.io/inject: "true"
spec:
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      name: test-deployment
      labels:
        app: test-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        envFrom:
        - secretRef:
            name: test-deployment
        - configMapRef:
            name: test-deployment
---
apiVersion: v1
kind: Secret
metadata:
  name: test-deployment
stringData: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-deployment
data: {}
```

**Comment by edwardecook** [comment]
cc @harshac
