### ISSUE TITLE
es-index-cleaner job fails on fresh es cluster

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger-operator#417]
In a fresh installation, es cluster does not have indices. In that case, `es-index-cleaner` job fails with the following error,

```
Traceback (most recent call last):
  File "/es-index-cleaner/esCleaner.py", line 88, in <module>
    main()
  File "/es-index-cleaner/esCleaner.py", line 49, in main
    filter_main_indices(ilo, prefix)
  File "/es-index-cleaner/esCleaner.py", line 64, in filter_main_indices
    ilo.filter_by_age(source='name', direction='older', timestring='%Y-%m-%d', unit='days', unit_count=int(sys.argv[1]))
  File "/usr/local/lib/python3.7/site-packages/curator/indexlist.py", line 500, in filter_by_age
    stats_result=stats_result
  File "/usr/local/lib/python3.7/site-packages/curator/indexlist.py", line 358, in _calculate_ages
    self._get_name_based_ages(timestring)
  File "/usr/local/lib/python3.7/site-packages/curator/indexlist.py", line 281, in _get_name_based_ages
    self.empty_list_check()
  File "/usr/local/lib/python3.7/site-packages/curator/indexlist.py", line 228, in empty_list_check
    raise exceptions.NoIndices('index_list object is empty.')
curator.exceptions.NoIndices: index_list object is empty.
``` 

CR file:
```yaml
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: true
      schedule: "*/10 * * * *"
      completedTTL: 1200
    dependencies:
      enabled: false
    elasticsearch:
      nodeCount: 3
      resources:
```

**Comment by pavolloffay** [comment]
It fails by desing see https://github.com/jaegertracing/jaeger/issues/1468. Let's track it upstream
