### ISSUE TITLE
Spark dependency jobs failing with streaming deployment

### ISSUE THREAD

**Issue by eroji** [jaegertracing/jaeger-operator#646]
I have a Jaeger deployment using the jaeger-operator and streaming type with Kafka deployed via the strimzi Kafka operator. The following is my instance config.

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: streaming
  collector:
    options:
      kafka: # <1>
        producer:
          topic: jaeger-spans
          brokers: jaeger-kafka-bootstrap:9092
  ingester:
    options:
      kafka: # <1>
        consumer:
          topic: jaeger-spans
          brokers: jaeger-kafka-bootstrap:9092
      ingester:
        deadlockInterval: 0 # <2>
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
    esIndexCleaner:
      enabled: true
      numberOfDays: 1
      schedule: "55 23 * * *"
      image: jaegertracing/jaeger-es-index-cleaner
  ingress:
    enabled: false
  agent:
    strategy: DaemonSet
    options:
      processor:
        jaeger-binary:
          server-queue-size: 5000
        jaeger-compact:
          server-queue-size: 5000
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 1
  collector:
    replicas: 2
    options:
      collector:
        num-workers: 100
        queue-size: 5000
```

However, when the spark dependency jobs kick off, all of them fail with the following stack trace.

```
19/09/05 00:45:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/09/05 00:45:24 INFO ElasticsearchDependenciesJob: Running Dependencies job for 2019-09-05T00:00Z, reading from jaeger-span-2019-09-05 index, result storing to jaeger-dependencies-2019-09-05
19/09/05 00:52:30 WARN NettyRpcEnv: Ignored failure: java.util.concurrent.TimeoutException: Cannot receive any reply from jaeger-spark-dependencies-1567641300-54mwx:45966 in 10 seconds
19/09/05 00:54:46 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:785)
at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:814)
at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:814)
at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:814)
at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1988)
at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:814)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
... 14 more
19/09/05 00:56:43 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 171120 ms exceeds timeout 120000 ms
19/09/05 01:03:48 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:785)
at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:814)
at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:814)
at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:814)
at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1988)
at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:814)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
... 14 more
19/09/05 01:07:54 ERROR TaskSchedulerImpl: Lost executor driver on localhost: Executor heartbeat timed out after 171120 ms
19/09/05 01:12:56 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:92)
at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:785)
at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply$mcV$sp(Executor.scala:814)
at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:814)
at org.apache.spark.executor.Executor$$anon$2$$anonfun$run$1.apply(Executor.scala:814)
at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1988)
at org.apache.spark.executor.Executor$$anon$2.run(Executor.scala:814)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
... 14 more
```

**Comment by objectiser** [comment]
There are some issues with your CR:
1) `strategy` should be `streaming`
2) `storage` node occurs twice - can you remove the first one which has `type: streaming` (which is not a storage type)
3) `collector` node occurs twice - can you combine the contents under a single node

@jpkrohling Is there any way to validate issues like this?

**Comment by jpkrohling** [comment]
For 1 and 2, we should have log messages in place, but an unknown storage should have made `in memory` as the effective storage type. Perhaps the ingester is being created, even though the storage type isn't `kafka` and strategy isn't `streaming`?

**Comment by jpkrohling** [comment]
About the point 3, not sure -- it all depends on how the yaml/json is deserialized into the Go type. We *could* override the unmarshalling routine, but instead of combining both into one node, we should really be rejecting the CR. There are things that are just too ambiguous to determine a good default: when there are conflicting nodes, which one should win? The first, or the last?

**Comment by objectiser** [comment]
> we should really be rejecting the CR

Agree - apart from options, which are more free format, some form of schema validation should pick up structural inconsistencies like this and reject the CR.

**Comment by eroji** [comment]
Thanks for pointing out the errors in the deployment yaml. I just copied and pasted blocks I found in the docs but did not appreciate the hierarchy it needed to be in.

**Comment by objectiser** [comment]
@eroji no problem - did it fix your issue?

**Comment by eroji** [comment]
> @eroji no problem - did it fix your issue?

Yes looks like it did. However, on a unrelated question, the streaming strategy seems to ensure the spans are complete (no more missing root span), but it appears the volume of spans it needs to process is causing it to lag behind quite a bit, upwards of 5+ minutes. What would you guys recommend in terms of tuning the CR to perhaps improve trace processing performance? The current CR has a 3 node ES backend.

**Comment by eroji** [comment]
Looks like the 5+ minutes plus estimate was too conservative. It's not able to keep up with the traces and will gradually fall further behind. It is around 40 minutes behind now. When I had the messages going straight to ES, although I would see many incomplete spans, it was at least populating every one of them with some traces near realtime. With streaming using Kafka, the processing appears to be in batches (correct me if I'm wrong). Perhaps there is a way to tune the frequency or batch size that the collector works on traces out of Kafka?

**Comment by objectiser** [comment]
Doesn't look like the ingester is as configurable in this area as the collector. There is an issue open to make [improvements to how batches ](https://github.com/jaegertracing/jaeger/issues/1696)are dealt with.

In the meantime, have you tried scaling up the ingester to see whether this helps reduce the delay?

**Comment by eroji** [comment]
I tried increasing replicas for injester to 1 per worker node, but the increasing lag remained.

**Comment by objectiser** [comment]
As this original issue has been solved, I would suggest closing this issue, and opening an issue on the jaeger repo specifically to deal with "ingester performance impact vs direct collector/elasticsearch". Hopefully other users that have a similar setup may be able to help there.

**Comment by eroji** [comment]
Sounds good. Thank you.
